-- MySQL Script generated by MySQL Workbench
-- Tue May 23 17:26:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pjbl_exp_criativa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pjbl_exp_criativa` ;

-- -----------------------------------------------------
-- Schema pjbl_exp_criativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pjbl_exp_criativa` DEFAULT CHARACTER SET utf8mb4 ;
USE `pjbl_exp_criativa` ;

-- -----------------------------------------------------
-- Table `pjbl_exp_criativa`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjbl_exp_criativa`.`users` ;

CREATE TABLE IF NOT EXISTS `pjbl_exp_criativa`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  `date_creation` DATE NOT NULL,
  `card_num_card` VARCHAR(16) NOT NULL,
  `card_name_owner` VARCHAR(50) NOT NULL,
  `card_cvv` VARCHAR(3) NOT NULL,
  `card_month_expire_date` INT(11) NOT NULL,
  `card_year_expire_date` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pjbl_exp_criativa`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjbl_exp_criativa`.`payments` ;

CREATE TABLE IF NOT EXISTS `pjbl_exp_criativa`.`payments` (
  `id_payment` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NULL DEFAULT NULL,
  `value` FLOAT NOT NULL,
  `month` INT(11) NOT NULL,
  `year` INT(11) NOT NULL,
  `is_paid` TINYINT(1) NOT NULL,
  `date_payment` DATE NOT NULL,
  `card_num_card` VARCHAR(16) NOT NULL,
  `card_name_owner` VARCHAR(50) NOT NULL,
  `card_cvv` VARCHAR(3) NOT NULL,
  `card_month_expire_date` INT(11) NOT NULL,
  `card_year_expire_date` INT(11) NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `payments_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `pjbl_exp_criativa`.`users` (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pjbl_exp_criativa`.`sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjbl_exp_criativa`.`sensors` ;

CREATE TABLE IF NOT EXISTS `pjbl_exp_criativa`.`sensors` (
  `id_sensor` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `model` VARCHAR(50) NOT NULL,
  `brand` VARCHAR(50) NOT NULL,
  `measure` VARCHAR(20) NOT NULL,
  `voltage` FLOAT NOT NULL,
  `register_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_sensor`),
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `sensors_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `pjbl_exp_criativa`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pjbl_exp_criativa`.`plants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjbl_exp_criativa`.`plants` ;

CREATE TABLE IF NOT EXISTS `pjbl_exp_criativa`.`plants` (
  `id_plant` INT(11) NOT NULL AUTO_INCREMENT,
  `id_sensor` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  `min_humidity` FLOAT NOT NULL,
  PRIMARY KEY (`id_plant`),
  INDEX `id_sensor` (`id_sensor` ASC) VISIBLE,
  CONSTRAINT `plants_ibfk_1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `pjbl_exp_criativa`.`sensors` (`id_sensor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pjbl_exp_criativa`.`records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjbl_exp_criativa`.`records` ;

CREATE TABLE IF NOT EXISTS `pjbl_exp_criativa`.`records` (
  `id_record` INT(11) NOT NULL AUTO_INCREMENT,
  `id_sensor` INT(11) NULL DEFAULT NULL,
  `value` FLOAT NOT NULL,
  `register_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_record`),
  INDEX `id_sensor` (`id_sensor` ASC) VISIBLE,
  CONSTRAINT `records_ibfk_1`
    FOREIGN KEY (`id_sensor`)
    REFERENCES `pjbl_exp_criativa`.`sensors` (`id_sensor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
